services:
  - type: web
    name: snowflake-dbt-analytics-engineering
    runtime: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
